CONSOLE
DECLARE FUNCTION Q()
FUNCTION Q()
STRING s
s = "CONSOLE.DECLARE FUNCTION Q().FUNCTION Q().STRING s.s = %!%.FOR i = 0 TO UBOUND(s).SELECT #s{i}.#33.?s;.#37.?CHR$(34);.#35.?%#%;.#63.?%?%;.#46.?.#ELSE.?CHR$(s{i});.END SELECT.NEXT i.?.END FUNCTION"
FOR i = 0 TO UBOUND(s)
SELECT CASE s{i}
CASE 33
PRINT s;
CASE 37
PRINT CHR$(34);
CASE 35
PRINT "CASE ";
CASE 63
PRINT "PRINT ";
CASE 46
PRINT 
CASE ELSE
PRINT CHR$(s{i});
END SELECT
NEXT i
PRINT 
END FUNCTION
